POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de ReactNative"
}

###
GET http://localhost:3333/courses?orderBy=title
# GET http://localhost:3333/courses?orderBy=title&page=3

###
GET http://localhost:3333/courses/5df9b60b-c512-4918-ae6b-e30d8536e7e6